xp01 xp01-all: xp01-parser libdir bindir
	$(TSC) -p src/xp01
	cp src/starter bin/xp01

xp01-watch:
	$(TSC) -w -p src/xp01

xp01-parser: lib/xp01/xp01-recipe.js

lib/xp01/xp01-recipe.js: src/xp01/xp01.ohm
	mkdir -p lib/xp01
	script/build-ohm.js $< $@

xp01-test:
	$(TAP) lib/xp01/test/*.js
